const BankData = [
  { id: 1, name: 'NH농협', img: '/images/bankImg/농협.png' },
  { id: 2, name: 'KB국민', img: '/images/bankImg/국민은행.png' },
  { id: 3, name: '신한', img: '/images/bankImg/신한-제주은행.png' },
  { id: 4, name: '우리', img: '/images/bankImg/우리은행.png' },
  { id: 5, name: '하나', img: '/images/bankImg/하나.png' },
  { id: 6, name: 'IBK기업', img: '/images/bankImg/기업.png' },
  { id: 7, name: '카카오뱅크', img: '/images/bankImg/카카오뱅크.png' },
  { id: 8, name: 'SC제일', img: '/images/bankImg/SC제일.png' },
  { id: 9, name: '씨티', img: '/images/bankImg/시티은행.png' },
  { id: 10, name: '제주', img: '/images/bankImg/신한-제주은행.png' },
  { id: 11, name: '새마을', img: '/images/bankImg/새마을금고.png' },
  { id: 12, name: 'KDB산업', img: '/images/bankImg/산업은행.png' },
  { id: 13, name: '저축', img: '/images/bankImg/저축은행.png' },
  { id: 14, name: '우체국', img: '/images/bankImg/우체국.png' },
  { id: 15, name: '대구은행', img: '/images/bankImg/대구은행.png' },
  { id: 16, name: '광주', img: '/images/bankImg/전북-광주은행.png' },
  { id: 17, name: '경남', img: '/images/bankImg/2.부산-경남.png' },
  { id: 18, name: '부산', img: '/images/bankImg/2.부산-경남.png' },
  { id: 19, name: '전북', img: '/images/bankImg/전북-광주은행.png' },
  { id: 20, name: '케이뱅크', img: '/images/bankImg/케이뱅크.png' },
  { id: 21, name: '산림조합', img: '/images/bankImg/산림조합중앙회.png' },
  { id: 22, name: '신협', img: '/images/bankImg/BankIcon.png' },
  { id: 23, name: '수협', img: '/images/bankImg/수협.png' },
  { id: 24, name: '광주', img: '/images/bankImg/전북-광주은행.png' },
  { id: 25, name: 'BOA', img: '/images/bankImg/뱅크오브아메리카.png' },
  { id: 26, name: 'HSBC', img: '/images/bankImg/HSBC.png' },
  { id: 28, name: '중국', img: '/images/bankImg/Vector.png' },
  { id: 29, name: '중국공상', img: '/images/bankImg/중국공산은행.png' },
  { id: 30, name: '도이치', img: '/images/bankImg/도이치은행.png' },
  { id: 31, name: 'JP모건', img: '/images/bankImg/jp모간체이스.png' },
  { id: 32, name: 'BNP파리바', img: '/images/bankImg/BNP파리바은행.png' },
  { id: 33, name: '중국건설은행', img: '/images/bankImg/중국건설은행.png' },
  { id: 34, name: '토스뱅크', img: '/images/bankImg/토스뱅크.png' },
];

export default BankData;
