const StockBankData = [
  { id: 35, name: '교보', img: '/images/bankImg/교보증권.png' },
  { id: 36, name: '대신', img: '/images/bankImg/대신증권.png' },
  { id: 37, name: 'DB금융투자', img: '/images/bankImg/동부증권.png' },
  { id: 38, name: '메리츠', img: '/images/bankImg/메리츠증권.png' },
  { id: 39, name: '미래에셋', img: '/images/bankImg/미래에셋증권.png' },
  { id: 40, name: '부국', img: '/images/bankImg/부국증권.png' },
  { id: 41, name: '삼성', img: '/images/bankImg/삼성증권.png' },
  { id: 42, name: '신영', img: '/images/bankImg/신영증권.png' },
  { id: 43, name: 'SK', img: '/images/bankImg/sk증권.png' },
  { id: 44, name: '현대차', img: '/images/bankImg/현대차증권.png' },
  { id: 45, name: '유안타', img: '/images/bankImg/유안타증권.png' },
  { id: 46, name: '유진투자', img: '/images/bankImg/유진투자증권.png' },
  { id: 47, name: '이베스트', img: '/images/bankImg/이베스트증권.png' },
  { id: 48, name: '케이프투자', img: '/images/bankImg/케이프투자증권.png' },
  { id: 49, name: '키움', img: '/images/bankImg/키움증권.png' },
  { id: 50, name: '한국포스', img: '/images/bankImg/한국포스증권.png' },
  { id: 51, name: '하나증권', img: '/images/bankImg/하나투자증권.png' },
  { id: 52, name: '하이투자', img: '/images/bankImg/하이투자증권.png' },
  { id: 53, name: '한국투자', img: '/images/bankImg/BankIcon.png' },
  { id: 54, name: '한화투자', img: '/images/bankImg/한화투자증권.png' },
  { id: 55, name: 'KB증권', img: '/images/bankImg/kb증권.png' },
  { id: 56, name: 'BNK투자', img: '/images/bankImg/2.부산-경남.png' },
  { id: 57, name: 'NH투자', img: '/images/bankImg/농협.png' },
  { id: 58, name: 'IBK투자', img: '/images/bankImg/기업.png' },
  { id: 59, name: '다올투자', img: '/images/bankImg/Group 1341.png' },
  { id: 60, name: '카카오페이', img: '/images/bankImg/카카오페이증권.png' },
  { id: 61, name: '토스', img: '/images/bankImg/토스증권.png' },
];
export default StockBankData;
